

/******* Functions Generated By Template Script *******/
extern hello_type print_hello(type1 arg1_name, type2 arg2_name);
extern hello_type print_hi(type1 arg1_name, type2 arg2_name);
extern hello_type print_howdy(type1 arg1_name, type2 arg2_name);
